### ISSUE TITLE
아이콘 추가 요청

### ISSUE THREAD

**Issue by kimjaeung** [knaram/onbill#3]
![image](https://user-images.githubusercontent.com/1704227/148926001-59a0d159-c460-44af-8aee-663267cd1e59.png)

매출처, 매입처, 기타의 아이콘이 type0-2 로 지정이 되어 있습니다.
아무것도 선택되지 않은 고객사의 경우에 아무것도 표시되지 않는 type이 필요합니다.

**Comment by knaram** [comment]
9, 10, 13, 17, 18.html 수정(9만 확인하셔도 됩니다.)
style.css 수정

    클래스 없음 : 선택되지 않음
    type0 : 기타
    type1 : 매출처
    type2 : 매입처                  
      
![온빌](https://user-images.githubusercontent.com/9690241/149265040-a108631b-46ba-473c-8e71-96a88981938a.png)
